# Workflow that runs on PRs and automates the integration & testing process
name: deploy-prd-app-to-azure

on:
  # Triggers the workflow on push events to main
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: cete-prd-api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'     
  NODE_VERSION: '14.x'               
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  release:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # Create an automatically bumped, indexed tag and push it to the branch
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      # Create a GH Release using the output of the tag_version step
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  # Test integration first before deploying
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create .env File
        run: |
          touch .env
          echo COSMOS_PRD_DB_CONN_STRING=${{ secrets.COSMOS_PRD_DB_CONN_STRING }} >> .env
          echo ENVIRONMENT=prd >> .env 
          cat .env

      # Install npm packages from the package JSON file
      - name: Install npm packages
        run: |
          npm install
      
      - name: Compile Typescript to JavaScript
        run: |
          npm run build --if-present

      - name: Install TypeScript eslint
        run: |
          npm install @typescript-eslint/eslint-plugin@latest --save-dev
      
      - name: Lint TypeScript
        run: |
          npm run lint --if-present
      
      # Remove unused packages from current build package, to reduce deployment time (artifact upload)
      - name: Remove Unused Packages
        run: |
          npm uninstall @types/mocha
          npm uninstall @typescript-eslint
          npm uninstall eslint
          npm uninstall eslint-scope
          npm uninstall eslint-utils
          npm uninstall eslint-visitor-keys
          npm uninstall mocha

      - name: Compress Build Files & Fix Permissions
        run: tar -cvf build_files.tar * .env

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: cete-api-app
          path: build_files.tar  

  deploy:

    runs-on: ubuntu-latest
    environment: production
    
    # Create dependency on test job to deploy
    needs: build

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v2
        with:
          name: cete-api-app

      - name: Decompress Artifact
        run: tar -xvf build_files.tar

      # Deploy app to Azure Functions App
      - name: Deploy to Cloud
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PRD_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
